{% set name = "jupyterlab_widgets" %}
{% set version = "3.0.15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/jupyterlab_widgets-{{ version }}.tar.gz
  sha256: 2920888a0c2922351a9202817957a68c07d99673504d6cd37345299e971bb08b

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<37]

requirements:
  host:
    - pip
    - python
    - hatchling >=1.5.0
    - hatch-jupyter-builder >=0.8.1
    - jupyterlab >=4,<5
  run:
    - python
  run_constrained:
    - jupyterlab >=3,<5

test:
  imports:
    - jupyterlab_widgets
  requires:
    - jupyterlab >=3,<5
    - msys2-grep  # [win]
    - pip
  commands:
    - pip check
    - jupyter labextension list
    - jupyter labextension list 1>labextensions 2>&1
    - "grep -iE \"@jupyter-widgets/jupyterlab-manager.*OK\" labextensions"

about:
  home: https://github.com/jupyter-widgets/ipywidgets
  summary: Jupyter interactive widgets for JupyterLab
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://github.com/jupyter-widgets/ipywidgets/tree/main/python/jupyterlab_widgets
  dev_url: https://github.com/jupyter-widgets/ipywidgets/tree/main/python/jupyterlab_widgets
  description: |
    A JupyterLab 3.0/4.0 extension for Jupyter/IPython widgets.

extra:
  recipe-maintainers:
    - jasongrout
    - SylvainCorlay
    - martinRenou
    - jtpio
    - bollwyvl