{% set name = "jupyterlab_widgets" %}
{% set version = "3.0.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jupyterlab_widgets-{{ version }}.tar.gz
  sha256: a2966d385328c1942b683a8cd96b89b8dd82c8b8f81dda902bb2bc06d46f5bed
build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: True # [py<37 or s390x]

requirements:
  host:
    - pip
    - python
    - jupyter-packaging >=0.10,<2
  run:
    - python
  run_constrained:
    - jupyterlab >=3,<5

test:
  imports:
    - jupyterlab_widgets
  commands:
    - pip check
    - jupyter labextension list
    - jupyter labextension list 1>labextensions 2>&1
    - grep -iE "@jupyter-widgets/jupyterlab-manager.*OK" labextensions
  requires:
    - jupyterlab
    - m2-grep  # [win]
    - pip

about:
  home: https://github.com/jupyter-widgets/ipywidgets
  summary: JupyterLab extension providing HTML widgets
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://github.com/jupyter-widgets/ipywidgets/tree/main/python/jupyterlab_widgets
  dev_url: https://github.com/jupyter-widgets/ipywidgets/tree/main/python/jupyterlab_widgets
  description: |
    A JupyterLab 3.0/4.0 extension for Jupyter/IPython widgets.

extra:
  recipe-maintainers:
    - jasongrout
    - SylvainCorlay
    - martinRenou
    - jtpio
    - bollwyvl
